### ISSUE TITLE
feat(Presidio): process nested objects within lists

### ISSUE THREAD

**Issue by dettanym** [dettanym/prose#2]
- [ ] Presidio's [batch analyzer](https://microsoft.github.io/presidio/samples/python/batch_processing/) doesn't support objects within lists. For example, Istio's bookinfo app involves requests with this structure. Either include support natively or [transform objects within lists](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.info.html) to a format that Presidio supports.

**Comment by dettanym** [comment]
- [ ] Create a test case to test Python / Presidio version upgrades

**Comment by qlonik** [comment]
This support landed recently in github.com/microsoft/presidio/pull/1192. See https://github.com/microsoft/presidio/blob/main/docs/samples/python/example_structured.ipynb for the example of using `presidio-structured` python package
