### ISSUE TITLE
Golang Envoy filter - OPA integration

### ISSUE THREAD

**Issue by dettanym** [dettanym/prose#55]
Communication with OPA: Passing in information via headers.
- Purpose of use: We've currently extracted pod labels from the X-Envoy-Peer-Metadata header and injected into the  X-Prose-Purpose header. (Note that this header may not be available on outgoing requests to mesh external domains: see https://github.com/istio/istio/issues/17635) 
- PII types: We've derived PII types using Presidio and injected them into the X-Prose-PII-types header. 

Each of these headers will be modified by each service proxy on each hop across microservices. So their values need to be base64 encodings of a JSON object map, not a string. The key of this object should be the span ID to avoid ambiguity. Can Envoy expose the span ID to any of the Decode/Encode StreamFilter API functions? Otherwise, we could use the service + API call name so if a key already exists, get its PII types / purpose, and append to its value of PII types or purposes?

**Comment by qlonik** [comment]
The scope of this issue is slightly changed: we are no longer going to pass the information to OPA sidecar via headers or baggage, since we now have OPA sdk built-in right into our golang filter.
